### ISSUE TITLE
Dependency problem with faraday 1.0.0

### ISSUE THREAD

**Issue by AkshayGoyal022** [looker/looker-sdk-ruby#107]
Hello,

We are trying to upgrade the elasticsearch gem to v7.6.0 which depends on Faraday ~> 1.0.0

The gem looker-sdk has a dependency on Faraday ['>= 0.9.0', '< 1.0']. We aren't able to upgrade elasticsearch because of this dependency.

Could you please review and try to fix this issue?

Thanks in advance!

**Comment by bertocq** [comment]
New version [just got released](https://github.com/looker/looker-sdk-ruby/releases/tag/v0.1.0), which [solves the issue](https://github.com/looker/looker-sdk-ruby/compare/v0.0.9...v0.1.0#diff-04d0aad79915fc5405d0d740a94c5306521c9eb138276695cca4075152b0ce9aR27)

Only problem is that it wasn't yet pushed to rubygems (https://rubygems.org/gems/looker-sdk/versions) so to use it you'll need to add to Gemfile:
```
gem 'looker-sdk', git: 'https://github.com/looker/looker-sdk-ruby.git', tag: 'v0.1.0'
```

Because at least for me just using `gem 'looker-sdk', '~> 0.1.0'` resulted in the following error:
![Screen Shot 2021-08-21 at 01 39 51](https://user-images.githubusercontent.com/983242/130303293-ddb07012-764b-47d4-8d8c-02cde9fef4cc.jpg)

**Comment by joeldodge79** [comment]
I'm working on getting `v0.1.0` published to rubygems but it might be a while so the `git: ..., tag: ...` Gemfile syntax is the way to go for now

**Comment by joeldodge79** [comment]
got `0.1.0` published to rubygems
