### ISSUE TITLE
JSONParse error on Postgres db error

### ISSUE THREAD

**Issue by cworsley4** [looker/looker-sdk-ruby#38]
@jbandhauer 
Not sure that this is an SDK issue as much as it is with the Looker API but I'll start here. I get a JSONParse error when there is a DB (Redshift/Postgres in this case) error thrown, when running a look. Judging by the error message the SDK throws the JSONParse error when it gets an unexpected response format from the looker instance. My thought is that an UnexpectedResponse exception of sorts should get thrown and that the API shouldn't be returning something that isn't in JSON format. This is how the API reports other errors it knows how to handle.

```
{
  "error": "Could not load model \"thelook\".",
  "error_detail": [
    "Model is not configured"
  ]
}

```
```
#<JSON::ParserError: unexpected token at 'SQL Error: ERROR: table 806669 dropped by concurrent transaction]'>

json/ext/Parser.java:251:in `parse'
/usr/local/lib/jruby-1.7.12/lib/ruby/shared/json/common.rb:155:in `parse'
/usr/local/lib/jruby-1.7.12/lib/ruby/shared/json/common.rb:334:in `load'
org/jruby/RubyMethod.java:128:in `call'
/var/www/looker/panopticon/releases/20150919190326/bundle/vendor/jruby/1.9/gems/sawyer-0.6.0/lib/sawyer/serializer.rb:62:in `decode'
/var/www/looker/panopticon/releases/20150919190326/bundle/vendor/jruby/1.9/gems/sawyer-0.6.0/lib/sawyer/agent.rb:125:in `decode_body'
/var/www/looker/panopticon/releases/20150919190326/bundle/vendor/jruby/1.9/bundler/gems/looker-sdk-ruby-a72323386700/lib/looker-sdk/sawyer_patch.rb:24:in `data'
/var/www/looker/panopticon/releases/20150919190326/bundle/vendor/jruby/1.9/bundler/gems/looker-sdk-ruby-a72323386700/lib/looker-sdk/client.rb:230:in `request'
/var/www/looker/panopticon/releases/20150919190326/bundle/vendor/jruby/1.9/bundler/gems/looker-sdk-ruby-a72323386700/lib/looker-sdk/client.rb:137:in `paginate'
/var/www/looker/panopticon/releases/20150919190326/bundle/vendor/jruby/1.9/bundler/gems/looker-sdk-ruby-a72323386700/lib/looker-sdk/client/dynamic.rb:96:in `invoke_remote'
/var/www/looker/panopticon/releases/20150919190326/bundle/vendor/jruby/1.9/bundler/gems/looker-sdk-ruby-a72323386700/lib/looker-sdk/client/dynamic.rb:63:in `method_missing'
/var/www/looker/panopticon/releases/20150919190326/lib/looker/permissions_api.rb:114:in `set_accounts_lists'
/var/www/looker/panopticon/releases/20150919190326/lib/looker/permissions_api.rb:80:in `update'
/var/www/looker/panopticon/releases/20150919190326/lib/looker/permissions_api.rb:32:in `initialize'
org/jruby/RubyKernel.java:1501:in `loop'
/var/www/looker/panopticon/releases/20150919190326/lib/looker/permissions_api.rb:31:in `initialize'

**Comment by jbandhauer** [comment]
Not an SDK bug. This is a known query API issue.

Note that for some query errors that occur after the results are already streaming we do intentionally embed errors into a 'success' response. That happens because if the error can't be detected until some of the rows are already streamed then there isn't a lot of choice; there is no good way to signal an error at that stage because HTTP requires setting the result code at the start of the response. So, if the error is detected after a bunch of rows have already been streamed then we just stick the error into the result stream and close the connection.

But, in this case we should be signalling the error better. This is a side effect of some legacy looker code on how it returns query errors to the browser.

**Comment by cworsley4** [comment]
Thanks for the info @jbandhauer. Thanks for passing this along to the right Helltool issue :+1:
