### ISSUE TITLE
I think it's time to publish this as a gem . . .

### ISSUE THREAD

**Issue by jgn** [looker/looker-sdk-ruby#42]
If one wants to leverage this in one's own gem: At present you can't specify it in a `.gemspec` 'cos it isn't published.

**Comment by squarism** [comment]
True that.  If you aren't doing a gem but a project/app, you can do this (for anyone out there) in your `Gemfile`:

`gem "looker-sdk", github: "looker/looker-sdk-ruby"`

Then run `bundle install`.  But yeah @jgn is right, you can't use git sources in `.gemspec` files because you can't expect people to build gems when they are just trying to use them.

🌻🌻🌻

**Comment by jgn** [comment]
I just want to say that this is increasingly driving me bananas. There are definitely use cases where `gem install` is helpful [example: for compliance reasons, one might prefer a system ruby] and the inability to specify this gem in one's `.gemspec` means you can't build on it.

**Comment by squarism** [comment]
This repo is MIT licensed, I wonder if it'd be legal/ok to just fork it as the published one and gem push it.  Then I guess you'd be taking on the support/syncing/publishing job of this repo.

**Comment by npickens** [comment]
@jgn @squarism Formally publishing as a gem is high up on our priority list for API/SDK work, so stay tuned!

**Comment by dthorpe** [comment]
https://rubygems.org/gems/looker-sdk
