### ISSUE TITLE
Sawyer version

### ISSUE THREAD

**Issue by florrain** [looker/looker-sdk-ruby#61]
Hi there,

Sawyer v0.6 is being enforced in the gemspec which itself is very strict on the addressable GEM version it uses. The next version 0.7 relaxes that constraint, so I could fork the repo and test with that version and authentication + a run_look were working fine. 

Going for the last version would be even better for everybody, since in between versions were only relaxing the dependencies: https://github.com/lostisland/sawyer/commits/master

I can write a PR for either:
- `s.add_dependency 'sawyer', '<= 0.8.1'`
- `s.add_dependency 'sawyer', '~> 0.8'`

Let me know what you think and thanks for the 💎 
Thanks

**Comment by dthorpe** [comment]
Hi Florrain, 

Thanks for the info! 

We're generally a little leery of setting version dependencies to always take latest, as we've occasionally been burned by breaking changes and bugs introduced in the bleeding edge latest release of a gem.

Let me check with folks here for confirmation about bumping the Sawyer version. Overall I think we'd be more comfortable with a fixed ceiling version spec rather than an open-ended version spec.

If you don't mind doing a PR, it'd be much appreciated! When I get 👍 from stakeholders here I can merge your PR.

Thanks!
-Danny
